### ISSUE TITLE
Can't spin during controller initialization. Spinner key hides spinner by default.

### ISSUE THREAD

**Issue by zhekaus** [urish/angular-spinner#55] opened 2015-08-12 07:24 UTC
If spinner placed inside ui-router template, the strange behavior is shown:
1)  If you specify spinner-key=’spinner-1’, the spinner is hided by default
2)  usSpinnerService.spin('spinner-1') doesn’t start spinning if it’s placed in controller of the view. I.e. the code bellow doesn't start spinner.

```
myApp.controller('Ctrl', function (usSpinnerService) {
    usSpinnerService.spin('spinner-1');
});
```

However, if the spinner resides outside the ui-router views, the everything is ok.

**Comment by bartes** [comment] 2015-08-26 17:12
This should help: https://github.com/bartes/angular-spinner/commit/81ffc7667e7a33baf9cded7a8400f171929fd70c

**Comment by Attrash-Islam** [comment] 2017-01-15 14:52
Duplicate of #26

Thanks @bartes

**Closed by Attrash-Islam** 2017-01-15 14:52 UTC
